<?php

use dmstr\helpers\Html;
use yii\bootstrap\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;

$colomn_2 = [
    'template' => '
    <div class="col-lg-12">
        <div class="col-md-4"><label class="control-label">{labelTitle}</label></div>
        <div class="col-md-8">{input}</div>
        <div class="col-md-12">{error}</div>
    </div>
        ',
    'options'=>['class'=>'col-md-6', 'style'=>'padding:0px;']
];
$hiddenTemplate = ["template" => "{input}"];
$hiddenStyle = ["style" => "display: none"];


DynamicFormWidget::begin([
    'widgetContainer' => 'dynamicform_wrapper_peserta', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
    'widgetBody' => '.peserta-items', // required: css class selector
    'widgetItem' => '.item-peserta', // required: css class
    'limit' => 999, // the maximum times, an element can be cloned (default 999)
    'min' => 1, // 0 or 1 (default 1)
    'insertButton' => '.add-item', // css class
    'deleteButton' => '.remove-item', // css class
    'model' => $modelPeserta[0],
    'formId' => 'Pelatihan',
    'formFields' => [
        'id',
        // 'pelatihan_id',
        'nik',
        'nama',
        'no_telp',
    ],
]);
?>


<div class="panel panel-default">
    <div class="panel-heading">
        <h4>
            <i class="glyphicon glyphicon-book"></i> Daftar Peserta
            <button type="button" class="add-item btn btn-success btn-sm pull-right"><i
                    class="glyphicon glyphicon-plus"></i> Add</button>
        </h4>
    </div>
    <div class="panel-body">
        <div class="container-items peserta-items">
            <!-- widgetBody -->

            <?php foreach ($modelPeserta as $i => $o): ?>
            <div class="item item-peserta panel panel-default">
                <!-- widgetItem -->
                <div class="panel-heading">
                    <h3 class="panel-title pull-left">Peserta</h3>
                    <div class="pull-right">
                        <button type="button" class="remove-item btn btn-danger btn-xs"><i
                                class="glyphicon glyphicon-minus"></i></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="panel-body">
                    <!-- <?php // $form->field($o, "[{$i}]id", $hiddenTemplate)->textInput($hiddenStyle)?> -->
                    <?= $form->field($o, "[{$i}]nik")->widget(\app\components\NikFinder::class, [
                            "pilihan" => [
                                'nama',
                                'no_telp',
                                'email',
                                'tempat_lahir',
                                'tanggal_lahir',
                                'jenis_kelamin_id',
                                'pekerjaan_id',
                                'pendidikan_id',
                                'alamat',
                                'rt',
                                'rw',
                                'desa_id',
                            ],
                            'otherModel' => $o,
                        ]) ?>
                    <?= $form->field($o, "[{$i}]nama", $colomn_2)->textInput() ?>
                    <?= $form->field($o, "[{$i}]no_telp", $colomn_2)->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]email", $colomn_2)->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]tempat_lahir", $colomn_2)->textInput() ?>
                    <?= $form->field($o, "[{$i}]tanggal_lahir", $colomn_2)->widget(\kartik\date\DatePicker::className(),
                        [
                            'pluginOptions' => [
                                'autoclose'=>true,
                                'format' => 'yyyy-mm-dd'
                            ]
                        ]) ?>
                    <?= $form->field($o, "[{$i}]jenis_kelamin_id", $colomn_2)->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\MasterJenisKelamin::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['jenis_kelamin_id'])),
                        ]
                    ); ?>
                    <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                    $form->field($o, "[{$i}]pekerjaan_id", $colomn_2)->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\MasterPekerjaan::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['pekerjaan_id'])),
                        ]
                    ); ?>
                    <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                    $form->field($o, "[{$i}]pendidikan_id", $colomn_2)->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\MasterPendidikan::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['pendidikan_id'])),
                        ]
                    ); ?>
                    <?= $form->field($o, "[{$i}]alamat", $colomn_2)->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]rt", $colomn_2)->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]rw", $colomn_2)->textInput(['maxlength' => true]) ?>
                    <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                    $form->field($o, "[{$i}]desa_id", $colomn_2)->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\WilayahDesa::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['desa_id'])),
                        ]
                    ); ?>
                    <hr>

                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div><!-- .panel -->

<?php
$this->registerJs('

    $(".dynamicform_wrapper_peserta").on("afterInsert", function(e, item_orang) {
        console.log("afterInsert");

        var btn = $(".btn-searc-nik");
        var id = btn.length-1;
        var prepare_attr = "["+id+"]nik";
        $(item_orang).find(btn).attr("btnId", id);
        $(item_orang).find(btn).attr("attribute", prepare_attr);
        $(item_orang).find(btn).attr("timestamp", e.timeStamp);


        var iAttribute = $(".input_attribute");
        $(item_orang).find(iAttribute).each(function(i, obj){
            $(obj).attr("marker", $(obj).attr("marker"));
        });

        var input = $(".input-nik");
        $(item_orang).find(input).attr("btnId", id);

        jQuery(".pilih_tanggal")
            .datepicker({"dateFormat":"yy-mm-dd","changeMonth":true,"changeYear":true});
    });

    $(".dynamicform_wrapper_peserta").on("beforeDelete", function(e, item_orang) {
        if (! confirm("Are you sure you want to delete this item?")) {
            return true;
        }
    });
');

?>
<?php DynamicFormWidget::end() ?>