<?php 
use yii\bootstrap\ActiveForm;
use wbraganca\dynamicform\DynamicFormWidget;


$hiddenTemplate = ["template" => "{input}"];
$hiddenStyle = ["style" => "display: none"];


DynamicFormWidget::begin([
    'widgetContainer' => 'dynamicform_wrapper_peserta', // required: only alphanumeric characters plus "_" [A-Za-z0-9_]
    'widgetBody' => '.peserta-items', // required: css class selector
    'widgetItem' => '.item-peserta', // required: css class
    'limit' => 999, // the maximum times, an element can be cloned (default 999)
    'min' => 1, // 0 or 1 (default 1)
    'insertButton' => '.add-item', // css class
    'deleteButton' => '.remove-item', // css class
    'model' => $modelPeserta[0],
    'formId' => 'Pelatihan',
    'formFields' => [
        'id',
        // 'pelatihan_id',
        'nik',
        'nama',
        'no_telp',
    ],
]);
?>


<div class="panel panel-default">
    <div class="panel-heading">
        <h4>
            <i class="glyphicon glyphicon-book"></i> Daftar Peserta
            <button type="button" class="add-item btn btn-success btn-sm pull-right"><i
                    class="glyphicon glyphicon-plus"></i> Add</button>
        </h4>
    </div>
    <div class="panel-body">
        <div class="container-items peserta-items">
            <!-- widgetBody -->

            <?php foreach ($modelPeserta as $i => $o): ?>
            <div class="item item-peserta panel panel-default">
                <!-- widgetItem -->
                <div class="panel-heading">
                    <h3 class="panel-title pull-left">Peserta</h3>
                    <div class="pull-right">
                        <button type="button" class="remove-item btn btn-danger btn-xs"><i
                                class="glyphicon glyphicon-minus"></i></button>
                    </div>
                    <div class="clearfix"></div>
                </div>
                <div class="panel-body">
                    <?=$form->field($o, "[{$i}]id", $hiddenTemplate)->textInput($hiddenStyle)?>
                    <?= $form->field($o, "[{$i}]nik")->textInput() ?>
                    <?= $form->field($o, "[{$i}]nama")->textInput() ?>
                    <?= $form->field($o, "[{$i}]no_telp")->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]email")->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]tempat_lahir")->textInput() ?>
                    <?= $form->field($o, "[{$i}]tanggal_lahir")->widget(\kartik\date\DatePicker::className(),
                        [
                            'pluginOptions' => [
                                'autoclose'=>true,
                                'format' => 'yyyy-mm-dd'
                            ]
                        ]) ?>
                    <?= $form->field($o, "[{$i}]jenis_kelamin_id")->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\MasterJenisKelamin::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['jenis_kelamin_id'])),
                        ]
                    ); ?>
                    <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                    $form->field($o, "[{$i}]pekerjaan_id")->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\MasterPekerjaan::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['pekerjaan_id'])),
                        ]
                    ); ?>
                    <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                    $form->field($o, "[{$i}]pendidikan_id")->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\MasterPendidikan::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['pendidikan_id'])),
                        ]
                    ); ?>
                    <?= $form->field($o, "[{$i}]alamat")->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]rt")->textInput(['maxlength' => true]) ?>
                    <?= $form->field($o, "[{$i}]rw")->textInput(['maxlength' => true]) ?>
                    <?= // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
                    $form->field($o, "[{$i}]desa_id")->dropDownList(
                        \yii\helpers\ArrayHelper::map(app\models\WilayahDesa::find()->all(), 'id', 'nama'),
                        [
                            'prompt' => 'Select',
                            'disabled' => (isset($relAttributes) && isset($relAttributes['desa_id'])),
                        ]
                    ); ?>
                    <hr>

                </div>
            </div>
            <?php endforeach; ?>
        </div>
    </div>
</div><!-- .panel -->

<?php DynamicFormWidget::end() ?>