<?php

use yii\grid\GridView;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\PelatihanSearch $searchModel
 */

$this->title = 'Pelatihan';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?=Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success'])?>
</p>


    <?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']])?>

    <div class="box box-info">
        <div class="box-body">
            <div class="table-responsive">
                <?=GridView::widget([
                    'layout' => '{summary}{pager}{items}{pager}',
                    'dataProvider' => $dataProvider,
                    'pager' => [
                        'class' => yii\widgets\LinkPager::className(),
                        'firstPageLabel' => 'First',
                        'lastPageLabel' => 'Last'],
                    'filterModel' => $searchModel,
                    'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                    'headerRowOptions' => ['class' => 'x'],
                    'columns' => [

                        \app\components\ActionButton::getButtons(),

                        'nama',
                        // 'latar_belakang:ntext',
                        // 'tujuan:ntext',
                        'tanggal_mulai',
                        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                        [
                            'class' => yii\grid\DataColumn::className(),
                            'attribute' => 'tingkat_id',
                            'value' => function ($model) {
                                if ($rel = $model->tingkat) {
                                    return Html::a($rel->nama, ['pelatihan-tingkat/view', 'id' => $rel->id], ['data-pjax' => 0]);
                                } else {
                                    return '';
                                }
                            },
                            'format' => 'raw',
                        ],
                        // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                        [
                            'class' => yii\grid\DataColumn::className(),
                            'attribute' => 'pelaksana_id',
                            'value' => function ($model) {
                                if ($rel = $model->pelaksana) {
                                    return Html::a($rel->name, ['user/view', 'id' => $rel->id], ['data-pjax' => 0]);
                                } else {
                                    return '';
                                }
                            },
                            'format' => 'raw',
                        ],
                        // 'modified_by',
                        /*'tanggal_selesai'*/
                        /*'modified_at'*/
                        /*// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                        [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'status_id',
                        'value' => function ($model) {
                        if ($rel = $model->status) {
                        return Html::a($rel->id, ['pelatihan-status/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                        } else {
                        return '';
                        }
                        },
                        'format' => 'raw',
                        ]*/
                        /*'forum_diskusi'*/
                    ],
                ]);?>
            </div>
        </div>
    </div>

    <?php \yii\widgets\Pjax::end()?>

