<?php

use dmstr\bootstrap\Tabs;
use dmstr\helpers\Html;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;

/**
 * @var yii\web\View $this
 * @var app\models\Pelatihan $model
 */

$this->title = 'Pelatihan ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pelatihan', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string) $model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud pelatihan-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?=Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id], ['class' => 'btn btn-info'])?>
        <?=Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success'])?>
    </p>
    <p class="pull-right">
        <?=Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Pelatihan', ['index'], ['class' => 'btn btn-default'])?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null): ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?=\Yii::$app->session->getFlash('deleteError')?>
        </span>
    <?php endif;?>

    <div class="box box-info">
        <div class="box-body">
            <?php $this->beginBlock('app\models\Pelatihan');?>

            <?=DetailView::widget([
                'model' => $model,
                'attributes' => [
                    'id',
                    'nama',
                    'latar_belakang:ntext',
                    'tujuan:ntext',
                    'tanggal_mulai',
                    'tanggal_selesai',
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'tingkat_id',
                        'value' => ($model->tingkat ?
                            Html::a('<i class="glyphicon glyphicon-list"></i>', ['pelatihan-tingkat/index']) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->tingkat->id, ['pelatihan-tingkat/view', 'id' => $model->tingkat->id]) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Pelatihan' => ['tingkat_id' => $model->tingkat_id]])
                            :
                            '<span class="label label-warning">?</span>'),
                    ],
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'status_id',
                        'value' => ($model->status ?
                            Html::a('<i class="glyphicon glyphicon-list"></i>', ['pelatihan-status/index']) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->status->id, ['pelatihan-status/view', 'id' => $model->status->id]) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Pelatihan' => ['status_id' => $model->status_id]])
                            :
                            '<span class="label label-warning">?</span>'),
                    ],
                    'forum_diskusi',
                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
                    [
                        'format' => 'html',
                        'attribute' => 'pelaksana_id',
                        'value' => ($model->pelaksana ?
                            Html::a('<i class="glyphicon glyphicon-list"></i>', ['user/index']) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> ' . $model->pelaksana->name, ['user/view', 'id' => $model->pelaksana->id]) . ' ' .
                            Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'Pelatihan' => ['pelaksana_id' => $model->pelaksana_id]])
                            :
                            '<span class="label label-warning">?</span>'),
                    ],
                    // 'created_at',
                    // 'created_by',
                    // 'modified_at',
                    // 'modified_by',
                ],
            ]);?>

            <hr/>

            <?=Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
                [
                    'class' => 'btn btn-danger',
                    'data-confirm' => '' . 'Are you sure to delete this item?' . '',
                    'data-method' => 'post',
                ]);?>
            <?php $this->endBlock();?>



            <?php $this->beginBlock('PelatihanLampirans');?>
            <div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
            <?=Html::a(
                    '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Pelatihan Lampirans',
                    ['pelatihan-lampiran/index'],
                    ['class' => 'btn text-muted btn-xs']
                )?>
            <?=Html::a(
                    '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Pelatihan Lampiran',
                    ['pelatihan-lampiran/create', 'PelatihanLampiran' => ['pelatihan_id' => $model->id]],
                    ['class' => 'btn btn-success btn-xs']
                );?>
            </div></div><?php Pjax::begin(['id' => 'pjax-PelatihanLampirans', 'enableReplaceState' => false, 'linkSelector' => '#pjax-PelatihanLampirans ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']])?>
            <?='<div class="table-responsive">'
            . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider([
                    'query' => $model->getPelatihanLampirans(),
                    'pagination' => [
                        'pageSize' => 20,
                        'pageParam' => 'page-pelatihanlampirans',
                    ],
                ]),
                'pager' => [
                    'class' => yii\widgets\LinkPager::class,
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last',
                ],
                'columns' => [
                    // [
                    //     'class' => 'yii\grid\ActionColumn',
                    //     'template' => '{view} {update}',
                    //     'contentOptions' => ['nowrap' => 'nowrap'],
                    //     'urlCreator' => function ($action, $model, $key, $index) {
                    //         // using the column name as key, not mapping to 'id' like the standard generator
                    //         $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    //         $params[0] = 'pelatihan-lampiran' . '/' . $action;
                    //         $params['PelatihanLampiran'] = ['pelatihan_id' => $model->primaryKey()[0]];
                    //         return $params;
                    //     },
                    //     'buttons' => [

                    //     ],
                    //     'controller' => 'pelatihan-lampiran',
                    // ],
                    // 'id',
                    [
                        'attribute' => 'judul_lampiran',
                        'format' => 'html',
                        'value' => function($model){
                            return "<a target='blank' href='{$model->getUploadedUrlFolder()}/{$model->file}'>$model->judul_lampiran";
                        }
                    ],
                    // 'file',
                ],
            ])
            . '</div>'?>
            <?php Pjax::end()?>
            <?php $this->endBlock()?>


            <?php $this->beginBlock('PelatihanPesertas');?>
            <div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
            <?=Html::a(
                    '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Pelatihan Pesertas',
                    ['pelatihan-peserta/index'],
                    ['class' => 'btn text-muted btn-xs']
                )?>
            <?=Html::a(
                    '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Pelatihan Peserta',
                    ['pelatihan-peserta/create', 'PelatihanPeserta' => ['pelatihan_id' => $model->id]],
                    ['class' => 'btn btn-success btn-xs']
                );?>
            </div></div><?php Pjax::begin(['id' => 'pjax-PelatihanPesertas', 'enableReplaceState' => false, 'linkSelector' => '#pjax-PelatihanPesertas ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']])?>
            <?='<div class="table-responsive">'
            . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider([
                    'query' => $model->getPelatihanPesertas(),
                    'pagination' => [
                        'pageSize' => 20,
                        'pageParam' => 'page-pelatihanpesertas',
                    ],
                ]),
                'pager' => [
                    'class' => yii\widgets\LinkPager::class,
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last',
                ],
                'columns' => [
                    // [
                    //     'class' => 'yii\grid\ActionColumn',
                    //     'template' => '{view} {update}',
                    //     'contentOptions' => ['nowrap' => 'nowrap'],
                    //     'urlCreator' => function ($action, $model, $key, $index) {
                    //         // using the column name as key, not mapping to 'id' like the standard generator
                    //         $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    //         $params[0] = 'pelatihan-peserta' . '/' . $action;
                    //         $params['PelatihanPeserta'] = ['pelatihan_id' => $model->primaryKey()[0]];
                    //         return $params;
                    //     },
                    //     'buttons' => [

                    //     ],
                    //     'controller' => 'pelatihan-peserta',
                    // ],
                    // 'id',
                    'nik',
                    'nama',
                    'no_telp',
                    'email:email',
                    'tempat_lahir',
                    'tanggal_lahir',
                    [
                        'attribute' => 'jenis_kelamin_id',
                        'value' => function($model){
                            return $model->jenisKelamin->nama;
                        }
                    ],
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                        'class' => yii\grid\DataColumn::class,
                        'attribute' => 'pekerjaan_id',
                        'value' => function ($model) {
                            return $model->pekerjaan->nama;
                        },
                        'format' => 'raw',
                    ],
                ],
            ])
            . '</div>'?>
            <?php Pjax::end()?>
            <?php $this->endBlock()?>


            <?php $this->beginBlock('PelatihanSoalJenis');?>
            <div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
            <!-- <?=Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Pelatihan Soal Jenis',
                ['pelatihan-soal-jenis/index'],
                ['class' => 'btn text-muted btn-xs']
            )?>
            <?=Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Pelatihan Soal Jenis',
                ['pelatihan-soal-jenis/create', 'PelatihanSoalJeni' => ['pelatihan_id' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            );?> -->
            </div></div><?php Pjax::begin(['id' => 'pjax-PelatihanSoalJenis', 'enableReplaceState' => false, 'linkSelector' => '#pjax-PelatihanSoalJenis ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']])?>
            <?='<div class="table-responsive">'
            . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider([
                    'query' => $model->getPelatihanSoalJenis(),
                    'pagination' => [
                        'pageSize' => 20,
                        'pageParam' => 'page-pelatihansoaljenis',
                    ],
                ]),
                'pager' => [
                    'class' => yii\widgets\LinkPager::class,
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last',
                ],
                'columns' => [
                    // [
                    //     'class' => 'yii\grid\ActionColumn',
                    //     'template' => '{view} {update}',
                    //     'contentOptions' => ['nowrap' => 'nowrap'],
                    //     'urlCreator' => function ($action, $model, $key, $index) {
                    //         // using the column name as key, not mapping to 'id' like the standard generator
                    //         $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                    //         $params[0] = 'pelatihan-soal-jenis' . '/' . $action;
                    //         $params['PelatihanSoalJenis'] = ['pelatihan_id' => $model->primaryKey()[0]];
                    //         return $params;
                    //     },
                    //     'buttons' => [

                    //     ],
                    //     'controller' => 'pelatihan-soal-jenis',
                    // ],
                    // 'id',
            // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                        'class' => yii\grid\DataColumn::class,
                        'attribute' => 'jenis_id',
                        'value' => function ($model) {
                            // if ($rel = $model->jenis) {
                                $rel = $model->jenis;
                                return $rel->nama;
                            // } 
                            // else {
                            //     return '';
                            // }
                        },
                        'format' => 'raw',
                    ],
                    'waktu_pengerjaan',
                    'jumlah_soal',
                ],
            ])
            . '</div>'?>
            <?php Pjax::end()?>
            <?php $this->endBlock()?>


            <?php $this->beginBlock('PelatihanSoalPilihanGandas');?>
            <div style='position: relative'><div style='position:absolute; right: 0px; top: 0px;'>
            <?=Html::a(
                '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Pelatihan Soal Pilihan Gandas',
                ['pelatihan-soal-pilihan-ganda/index'],
                ['class' => 'btn text-muted btn-xs']
            )?>
            <?=Html::a(
                '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Pelatihan Soal Pilihan Ganda',
                ['pelatihan-soal-pilihan-ganda/create', 'PelatihanSoalPilihanGanda' => ['pelatihan_soal_id' => $model->id]],
                ['class' => 'btn btn-success btn-xs']
            );?>
            </div></div><?php Pjax::begin(['id' => 'pjax-PelatihanSoalPilihanGandas', 'enableReplaceState' => false, 'linkSelector' => '#pjax-PelatihanSoalPilihanGandas ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']])?>
            <?='<div class="table-responsive">'
            . \yii\grid\GridView::widget([
                'layout' => '{summary}{pager}<br/>{items}{pager}',
                'dataProvider' => new \yii\data\ActiveDataProvider([
                    'query' => $model->getPelatihanSoalPilihanGandas(),
                    'pagination' => [
                        'pageSize' => 20,
                        'pageParam' => 'page-pelatihansoalpilihangandas',
                    ],
                ]),
                'pager' => [
                    'class' => yii\widgets\LinkPager::class,
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last',
                ],
                'columns' => [
                    [
                        'class' => 'yii\grid\ActionColumn',
                        'template' => '{view} {update}',
                        'contentOptions' => ['nowrap' => 'nowrap'],
                        'urlCreator' => function ($action, $model, $key, $index) {
                            // using the column name as key, not mapping to 'id' like the standard generator
                            $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
                            $params[0] = 'pelatihan-soal-pilihan-ganda' . '/' . $action;
                            $params['PelatihanSoalPilihanGanda'] = ['pelatihan_soal_id' => $model->primaryKey()[0]];
                            return $params;
                        },
                        'buttons' => [

                        ],
                        'controller' => 'pelatihan-soal-pilihan-ganda',
                    ],
                    'id',
                    'jawaban',
                ],
            ])
            . '</div>'?>
            <?php Pjax::end()?>
            <?php $this->endBlock()?>


            <?=Tabs::widget(
                [
                    'id' => 'relation-tabs',
                    'encodeLabels' => false,
                    'items' => [[
                        'label' => '<b class=""># ' . $model->id . '</b>',
                        'content' => $this->blocks['app\models\Pelatihan'],
                        'active' => true,
                    ], [
                        'content' => $this->blocks['PelatihanLampirans'],
                        'label' => '<small>Pelatihan Lampirans <span class="badge badge-default">' . count($model->getPelatihanLampirans()->asArray()->all()) . '</span></small>',
                        'active' => false,
                    ], [
                        'content' => $this->blocks['PelatihanPesertas'],
                        'label' => '<small>Pelatihan Pesertas <span class="badge badge-default">' . count($model->getPelatihanPesertas()->asArray()->all()) . '</span></small>',
                        'active' => false,
                    ], [
                        'content' => $this->blocks['PelatihanSoalJenis'],
                        'label' => '<small>Pelatihan Soal Jenis <span class="badge badge-default">' . count($model->getPelatihanSoalJenis()->asArray()->all()) . '</span></small>',
                        'active' => false,
                    ], [
                        'content' => $this->blocks['PelatihanSoalPilihanGandas'],
                        'label' => '<small>Pelatihan Soal Pilihan Gandas <span class="badge badge-default">' . count($model->getPelatihanSoalPilihanGandas()->asArray()->all()) . '</span></small>',
                        'active' => false,
                    ]],
                ]
            );
            ?>
        </div>
    </div>
</div>
