<?php

use yii\grid\GridView;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var yii\data\ActiveDataProvider $dataProvider
 * @var app\models\search\PelatihanPesertaSearch $searchModel
 */

$this->title = 'Pelatihan Peserta';
$this->params['breadcrumbs'][] = $this->title;
?>

<p>
    <?=Html::a('<i class="fa fa-plus"></i> Tambah Baru', ['create'], ['class' => 'btn btn-success'])?>
</p>


    <?php \yii\widgets\Pjax::begin(['id' => 'pjax-main', 'enableReplaceState' => false, 'linkSelector' => '#pjax-main ul.pagination a, th a', 'clientOptions' => ['pjax:success' => 'function(){alert("yo")}']])?>

    <div class="box box-info">
        <div class="box-body">
            <div class="table-responsive">
                <?=GridView::widget([
                'layout' => '{summary}{pager}{items}{pager}',
                'dataProvider' => $dataProvider,
                'pager' => [
                    'class' => yii\widgets\LinkPager::className(),
                    'firstPageLabel' => 'First',
                    'lastPageLabel' => 'Last'],
                'filterModel' => $searchModel,
                'tableOptions' => ['class' => 'table table-striped table-bordered table-hover'],
                'headerRowOptions' => ['class' => 'x'],
                'columns' => [

                    \app\components\ActionButton::getButtons(),

                    // generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                        'class' => yii\grid\DataColumn::className(),
                        'attribute' => 'pelatihan_id',
                        'value' => function ($model) {
                            if ($rel = $model->pelatihan) {
                                return Html::a($rel->id, ['pelatihan/view', 'id' => $rel->id], ['data-pjax' => 0]);
                            } else {
                                return '';
                            }
                        },
                        'format' => 'raw',
                    ],
                    'nik',
                    'nama',
                    'email:email',
                    'no_telp',
                    'tanggal_lahir',
                    'tempat_lahir',
                    /*// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'jenis_kelamin_id',
                    'value' => function ($model) {
                    if ($rel = $model->jenisKelamin) {
                    return Html::a($rel->id, ['master-jenis-kelamin/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                    } else {
                    return '';
                    }
                    },
                    'format' => 'raw',
                    ]*/
                    /*// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'pendidikan_id',
                    'value' => function ($model) {
                    if ($rel = $model->pendidikan) {
                    return Html::a($rel->id, ['master-pendidikan/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                    } else {
                    return '';
                    }
                    },
                    'format' => 'raw',
                    ]*/
                    /*// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'pekerjaan_id',
                    'value' => function ($model) {
                    if ($rel = $model->pekerjaan) {
                    return Html::a($rel->id, ['master-pekerjaan/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                    } else {
                    return '';
                    }
                    },
                    'format' => 'raw',
                    ]*/
                    /*'rt'*/
                    /*'rw'*/
                    /*'alamat:ntext'*/
                    /*// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::columnFormat
                    [
                    'class' => yii\grid\DataColumn::className(),
                    'attribute' => 'desa_id',
                    'value' => function ($model) {
                    if ($rel = $model->desa) {
                    return Html::a($rel->id, ['wilayah-desa/view', 'id' => $rel->id,], ['data-pjax' => 0]);
                    } else {
                    return '';
                    }
                    },
                    'format' => 'raw',
                    ]*/
                    /*'password'*/
                    /*'peserta_konfirmasi'*/
                    /*'nilai_pretest'*/
                    /*'nilai_posttest'*/
                    /*'nilai_praktek'*/
                    /*'kesibukan_pasca_pelatihan'*/
                    /*'masa_berlaku'*/
                    /*'lanjut'*/
                    /*'komentar:ntext'*/
                    /*'lokasi:ntext'*/
                    /*'jenis_izin_usaha:ntext'*/
                    /*'nib:ntext'*/
                    /*'nama_usaha'*/
                    /*'jenis_usaha'*/
                ],
            ]);?>
            </div>
        </div>
    </div>

    <?php \yii\widgets\Pjax::end()?>

