<?php

use dmstr\helpers\Html;
use yii\helpers\Url;
use yii\grid\GridView;
use yii\widgets\DetailView;
use yii\widgets\Pjax;
use app\components\mazer\Tabs;

/**
* @var yii\web\View $this
* @var app\models\PelatihanSoal $model
*/

$this->title = 'Pelatihan Soal ' . $model->id;
$this->params['breadcrumbs'][] = ['label' => 'Pelatihan Soal', 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => (string)$model->id, 'url' => ['view', 'id' => $model->id]];
$this->params['breadcrumbs'][] = 'View';
?>
<div class="giiant-crud pelatihan-soal-view">

    <!-- menu buttons -->
    <p class='pull-left'>
        <?= Html::a('<span class="glyphicon glyphicon-pencil"></span> ' . 'Edit', ['update', 'id' => $model->id],['class' => 'btn btn-info']) ?>
        <?= Html::a('<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru', ['create'], ['class' => 'btn btn-success']) ?>
    </p>
    <p class="pull-right">
        <?= Html::a('<span class="glyphicon glyphicon-list"></span> ' . 'Daftar Pelatihan Soal', ['index'], ['class'=>'btn btn-default']) ?>
    </p>

    <div class="clearfix"></div>

    <!-- flash message -->
    <?php if (\Yii::$app->session->getFlash('deleteError') !== null) : ?>
        <span class="alert alert-info alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span></button>
            <?= \Yii::$app->session->getFlash('deleteError') ?>
        </span>
    <?php endif; ?>

    <div class="card card-default">
        <div class="card-body">
            <?php $this->beginBlock('app\models\PelatihanSoal'); ?>

            <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                    'id',
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'jenis_id',
    'value' => ($model->jenis ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['pelatihan-soal-jenis/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->jenis->id, ['pelatihan-soal-jenis/view', 'id' => $model->jenis->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PelatihanSoal'=>['jenis_id' => $model->jenis_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::attributeFormat
[
    'format' => 'html',
    'attribute' => 'kategori_soal_id',
    'value' => ($model->kategoriSoal ? 
        Html::a('<i class="glyphicon glyphicon-list"></i>', ['master-kategori-soal/index']).' '.
        Html::a('<i class="glyphicon glyphicon-circle-arrow-right"></i> '.$model->kategoriSoal->id, ['master-kategori-soal/view', 'id' => $model->kategoriSoal->id,]).' '.
        Html::a('<i class="glyphicon glyphicon-paperclip"></i>', ['create', 'PelatihanSoal'=>['kategori_soal_id' => $model->kategori_soal_id]])
        : 
        '<span class="label label-warning">?</span>'),
],
        // 'nomor',
        'soal:ntext',
        'pilihan:ntext',
        'jawaban:ntext',
            ],
            ]); ?>

            <hr/>

            <?= Html::a('<span class="glyphicon glyphicon-trash"></span> ' . 'Delete', ['delete', 'id' => $model->id],
            [
            'class' => 'btn btn-danger',
            'data-confirm' => '' . 'Are you sure to delete this item?' . '',
            'data-method' => 'post',
            ]); ?>
            <?php $this->endBlock(); ?>


            
<?php $this->beginBlock('PelatihanSoalPesertaJawabans'); ?>
<div style='position: relative'><div style='position:absolute; right: 0px; top 0px;'>
  <?= Html::a(
            '<span class="glyphicon glyphicon-list"></span> ' . 'List All' . ' Pelatihan Soal Peserta Jawabans',
            ['pelatihan-soal-peserta-jawaban/index'],
            ['class'=>'btn text-muted btn-xs']
        ) ?>
  <?= Html::a(
            '<span class="glyphicon glyphicon-plus"></span> ' . 'Tambah Baru' . ' Pelatihan Soal Peserta Jawaban',
            ['pelatihan-soal-peserta-jawaban/create', 'PelatihanSoalPesertaJawaban' => ['soal_id' => $model->id]],
            ['class'=>'btn btn-success btn-xs']
        ); ?>
</div></div><?php Pjax::begin(['id'=>'pjax-PelatihanSoalPesertaJawabans', 'enableReplaceState'=> false, 'linkSelector'=>'#pjax-PelatihanSoalPesertaJawabans ul.pagination a, th a', 'clientOptions' => ['pjax:success'=>'function(){alert("yo")}']]) ?>
<?= '<div class="table-responsive">'
 . \yii\grid\GridView::widget([
    'layout' => '{summary}{pager}<br/>{items}{pager}',
    'dataProvider' => new \yii\data\ActiveDataProvider([
        'query' => $model->getPelatihanSoalPesertaJawabans(),
        'pagination' => [
            'pageSize' => 20,
            'pageParam'=>'page-pelatihansoalpesertajawabans',
        ]
    ]),
    'pager'        => [
        'class'          => app\components\mazer\LinkPager::className(),
        'firstPageLabel' => 'First',
        'lastPageLabel'  => 'Last'
    ],
    'columns' => [
 [
    'class'      => 'yii\grid\ActionColumn',
    'template'   => '{view} {update}',
    'contentOptions' => ['nowrap'=>'nowrap'],
    'urlCreator' => function ($action, $model, $key, $index) {
        // using the column name as key, not mapping to 'id' like the standard generator
        $params = is_array($key) ? $key : [$model->primaryKey()[0] => (string) $key];
        $params[0] = 'pelatihan-soal-peserta-jawaban' . '/' . $action;
        $params['PelatihanSoalPesertaJawaban'] = ['soal_id' => $model->primaryKey()[0]];
        return $params;
    },
    'buttons'    => [
        
    ],
    'controller' => 'pelatihan-soal-peserta-jawaban'
],
        'id',

[
    'class' => yii\grid\DataColumn::className(),
    'attribute' => 'peserta_id',
    'value' => function ($model) {
        if ($rel = $model->peserta) {
            return Html::a($rel->id, ['pelatihan-peserta/view', 'id' => $rel->id,], ['data-pjax' => 0]);
        } else {
            return '';
        }
    },
    'format' => 'raw',
],
        'jawaban:ntext',
]
])
 . '</div>' ?>
<?php Pjax::end() ?>
<?php $this->endBlock() ?>


            <?= Tabs::widget(
                 [
                     'id' => 'relation-tabs',
                     'encodeLabels' => false,
                     'items' => [ [
    'label'   => '<b class=""># '.$model->id.'</b>',
    'content' => $this->blocks['app\models\PelatihanSoal'],
    'active'  => true,
],[
    'content' => $this->blocks['PelatihanSoalPesertaJawabans'],
    'label'   => '<small>Pelatihan Soal Peserta Jawabans <span class="badge badge-default">'.count($model->getPelatihanSoalPesertaJawabans()->asArray()->all()).'</span></small>',
    'active'  => false,
], ]
                 ]
    );
    ?>
        </div>
    </div>
</div>
