<?php

use yii\bootstrap\ActiveForm;
use yii\helpers\Html;

/**
 * @var yii\web\View $this
 * @var app\models\PelatihanLampiran $model
 * @var yii\widgets\ActiveForm $form
 */

?>

<div class="card card-default">
    <div class="card-body">
        <?php $form = ActiveForm::begin([
            'id' => 'PelatihanLampiran',
            'layout' => 'horizontal',
            'enableClientValidation' => true,
            'errorSummaryCssClass' => 'error-summary alert alert-error',
        ]);
        ?>

			<?=$form->field($model, 'id')->textInput()?>
			<?=// generated by schmunk42\giiant\generators\crud\providers\core\RelationProvider::activeField
            $form->field($model, 'pelatihan_id')->dropDownList(
                \yii\helpers\ArrayHelper::map(app\models\Pelatihan::find()->all(), 'id', 'id'),
                [
                    'prompt' => 'Select',
                    'disabled' => (isset($relAttributes) && isset($relAttributes['pelatihan_id'])),
                ]
            );?>
			<?=$form->field($model, 'judul_lampiran')->textInput(['maxlength' => true])?>
			<?=$form->field($model, 'file')->textInput(['maxlength' => true])?>        <hr/>
        <?php echo $form->errorSummary($model); ?>
        <div class="row">
            <div class="col-md-offset-3 col-md-10">
                <?=Html::submitButton('<i class="fa fa-save"></i> Simpan', ['class' => 'btn btn-success']);?>
                <?=Html::a('<i class="fa fa-chevron-left"></i> Kembali', ['index'], ['class' => 'btn btn-default'])?>
            </div>
        </div>

        <?php ActiveForm::end();?>

    </div>
</div>