<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "master_kategori_soal".
 *
 * @property integer $id
 * @property string $nama
 * @property integer $flag
 *
 * @property \app\models\PelatihanSoal[] $pelatihanSoals
 * @property string $aliasModel
 */
abstract class KategoriSoal extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_kategori_soal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama'], 'required'],
            [['flag'], 'integer'],
            [['nama'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nama' => 'Nama',
            'flag' => 'Flag',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nama' => 'jenis soal , ex : multiple choice, esay, short answer',
            'flag' => '0 = deleted, 1 = active',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSoals()
    {
        return $this->hasMany(\app\models\PelatihanSoal::className(), ['kategori_soal_id' => 'id']);
    }




}
