<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "master_kuesioner_monev".
 *
 * @property integer $id
 * @property string $pertanyaan
 * @property string $jawaban
 * @property integer $flag
 *
 * @property \app\models\PelatihanKuisionerMonev[] $pelatihanKuisionerMonevs
 * @property string $aliasModel
 */
abstract class MasterKuesionerMonev extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'master_kuesioner_monev';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pertanyaan', 'jawaban'], 'required'],
            [['flag'], 'integer'],
            [['pertanyaan'], 'string', 'max' => 200],
            [['jawaban'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pertanyaan' => 'Pertanyaan',
            'jawaban' => 'Jawaban',
            'flag' => 'Flag',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanKuesionerMonevs()
    {
        return $this->hasMany(\app\models\PelatihanKuesionerMonev::className(), ['soal' => 'id']);
    }




}
