<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pelatihan_kuesioner_monev".
 *
 * @property integer $id
 * @property integer $jenis_id
 * @property integer $peserta_id
 * @property integer $soal
 * @property string $jawaban
 *
 * @property \app\models\PelatihanPeserta $peserta
 * @property \app\models\MasterKuesionerMonev $soal0
 * @property \app\models\PelatihanSoalJenis $jenis
 * @property string $aliasModel
 */
abstract class PelatihanKuesionerMonev extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelatihan_kuesioner_monev';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['jenis_id', 'peserta_id', 'soal'], 'required'],
            [['jenis_id', 'peserta_id', 'soal'], 'integer'],
            [['jawaban'], 'string'],
            [['peserta_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PelatihanPeserta::className(), 'targetAttribute' => ['peserta_id' => 'id']],
            [['soal'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterKuesionerMonev::className(), 'targetAttribute' => ['soal' => 'id']],
            [['jenis_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PelatihanSoalJenis::className(), 'targetAttribute' => ['jenis_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'jenis_id' => 'Jenis ID',
            'peserta_id' => 'Peserta ID',
            'soal' => 'Soal',
            'jawaban' => 'Jawaban',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPeserta()
    {
        return $this->hasOne(\app\models\PelatihanPeserta::className(), ['id' => 'peserta_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSoal0()
    {
        return $this->hasOne(\app\models\MasterKuesionerMonev::className(), ['id' => 'soal']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenis()
    {
        return $this->hasOne(\app\models\PelatihanSoalJenis::className(), ['id' => 'jenis_id']);
    }




}
