<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pelatihan_peserta".
 *
 * @property integer $id
 * @property integer $pelatihan_id
 * @property string $nik
 * @property string $nama
 * @property string $no_telp
 * @property string $email
 * @property string $tempat_lahir
 * @property string $tanggal_lahir
 * @property integer $jenis_kelamin_id
 * @property integer $pekerjaan_id
 * @property integer $pendidikan_id
 * @property string $alamat
 * @property integer $rt
 * @property integer $rw
 * @property integer $desa_id
 *
 * @property \app\models\Pelatihan $pelatihan
 * @property \app\models\MasterPekerjaan $pekerjaan
 * @property \app\models\MasterPekerjaan $pekerjaan0
 * @property \app\models\MasterPendidikan $pendidikan
 * @property \app\models\MasterJenisKelamin $jenisKelamin
 * @property \app\models\WilayahDesa $desa
 * @property \app\models\PelatihanSoalPeserta[] $pelatihanSoalPesertas
 * @property \app\models\PelatihanSoalPesertaJawaban[] $pelatihanSoalPesertaJawabans
 * @property \app\models\User[] $users
 * @property string $aliasModel
 */
abstract class PelatihanPeserta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelatihan_peserta';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pelatihan_id', 'nik', 'nama', 'no_telp', 'email', 'tempat_lahir', 'tanggal_lahir', 'jenis_kelamin_id', 'pekerjaan_id', 'pendidikan_id', 'alamat', 'desa_id'], 'required'],
            [['pelatihan_id', 'jenis_kelamin_id', 'pekerjaan_id', 'pendidikan_id', 'rt', 'rw', 'desa_id'], 'integer'],
            [['nik', 'no_telp'], 'string', 'max' => 20],
            [['nama', 'email', 'tempat_lahir', 'tanggal_lahir', 'alamat'], 'string', 'max' => 100],
            [['pelatihan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pelatihan::className(), 'targetAttribute' => ['pelatihan_id' => 'id']],
            [['pekerjaan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterPekerjaan::className(), 'targetAttribute' => ['pekerjaan_id' => 'id']],
            [['pekerjaan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterPekerjaan::className(), 'targetAttribute' => ['pekerjaan_id' => 'id']],
            [['pendidikan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterPendidikan::className(), 'targetAttribute' => ['pendidikan_id' => 'id']],
            [['jenis_kelamin_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterJenisKelamin::className(), 'targetAttribute' => ['jenis_kelamin_id' => 'id']],
            [['desa_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahDesa::className(), 'targetAttribute' => ['desa_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pelatihan_id' => 'Pelatihan ID',
            'nik' => 'Nik',
            'nama' => 'Nama',
            'no_telp' => 'No Telp',
            'email' => 'Email',
            'tempat_lahir' => 'Tempat Lahir',
            'tanggal_lahir' => 'Tanggal Lahir',
            'jenis_kelamin_id' => 'Jenis Kelamin ID',
            'pekerjaan_id' => 'Pekerjaan ID',
            'pendidikan_id' => 'Pendidikan ID',
            'alamat' => 'Alamat',
            'rt' => 'Rt',
            'rw' => 'Rw',
            'desa_id' => 'Desa ID',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'pelatihan_id' => 'pelatihan yang sedang diikuti',
            'no_telp' => 'nomer telepon',
            'email' => 'alamat surel',
            'jenis_kelamin_id' => 'jenis kelamin',
            'pekerjaan_id' => 'pekerjaan saat ini',
            'pendidikan_id' => 'pendidikan terakhir yang ditempuh',
            'alamat' => 'alamat domisili',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihan()
    {
        return $this->hasOne(\app\models\Pelatihan::className(), ['id' => 'pelatihan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPekerjaan()
    {
        return $this->hasOne(\app\models\MasterPekerjaan::className(), ['id' => 'pekerjaan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPekerjaan0()
    {
        return $this->hasOne(\app\models\MasterPekerjaan::className(), ['id' => 'pekerjaan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPendidikan()
    {
        return $this->hasOne(\app\models\MasterPendidikan::className(), ['id' => 'pendidikan_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenisKelamin()
    {
        return $this->hasOne(\app\models\MasterJenisKelamin::className(), ['id' => 'jenis_kelamin_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDesa()
    {
        return $this->hasOne(\app\models\WilayahDesa::className(), ['id' => 'desa_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSoalPesertas()
    {
        return $this->hasMany(\app\models\PelatihanSoalPeserta::className(), ['peserta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSoalPesertaJawabans()
    {
        return $this->hasMany(\app\models\PelatihanSoalPesertaJawaban::className(), ['peserta_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUsers()
    {
        return $this->hasMany(\app\models\User::className(), ['peserta_pelatihan_id' => 'id']);
    }




}
