<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pelatihan_jenis".
 *
 * @property integer $id
 * @property string $index
 * @property string $nama
 * @property string $sasaran
 * @property string $peserta
 * @property string $durasi
 * @property string $instansi_id
 * @property string $aliasModel
 */
abstract class PelatihanJenis extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelatihan_jenis';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['index', 'nama'], 'required'],
            [['index'], 'string', 'max' => 5],
            [['nama', 'sasaran'], 'string', 'max' => 200],
            [['peserta'], 'string', 'max' => 10],
            [['durasi'], 'string', 'max' => 50],
            [['instansi_id'], 'string', 'max' => 100]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'index' => 'Index',
            'nama' => 'Nama',
            'sasaran' => 'Sasaran',
            'peserta' => 'Peserta',
            'durasi' => 'Durasi',
            'instansi_id' => 'Instansi ID',
        ];
    }




}
