<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pelatihan_lampiran".
 *
 * @property integer $id
 * @property integer $pelatihan_id
 * @property string $judul_lampiran
 * @property string $file
 *
 * @property \app\models\Pelatihan $pelatihan
 * @property string $aliasModel
 */
abstract class PelatihanLampiran extends \yii\db\ActiveRecord
{

    public $image;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelatihan_lampiran';
    }
    
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['judul_lampiran', 'file'], 'required'],
            [['pelatihan_id'], 'integer'],
            [['judul_lampiran', 'file'], 'string', 'max' => 100],
            [['image'], 'file', 'extensions' => 'doc,docx,xls,xlsx', 'mimeTypes' => 'application/msword,application/vnd.ms-excel', 'skipOnEmpty' => true, 'on' => 'update'],
            [['image'], 'file', 'extensions' => 'doc,docx,xls,xlsx', 'mimeTypes' => 'application/msword,application/vnd.ms-excel', 'skipOnEmpty' => false, 'on' => 'create'],
            [['pelatihan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pelatihan::className(), 'targetAttribute' => ['pelatihan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pelatihan_id' => 'Pelatihan ID',
            'judul_lampiran' => 'Judul Lampiran',
            'image' => 'Dokumen',
            'file' => 'File',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihan()
    {
        return $this->hasOne(\app\models\Pelatihan::className(), ['id' => 'pelatihan_id']);
    }




}
