<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pelatihan_soal".
 *
 * @property integer $id
 * @property string $unique_id
 * @property integer $jenis_id
 * @property integer $kategori_soal_id
 * @property integer $nomor
 * @property string $soal
 * @property string $pilihan
 * @property string $jawaban
 * @property integer $order
 * @property integer $nilai_maksimum
 *
 * @property \app\models\MasterKategoriSoal $kategoriSoal
 * @property \app\models\PelatihanSoalJenis $jenis
 * @property \app\models\PelatihanSoalPesertaJawaban[] $pelatihanSoalPesertaJawabans
 * @property \app\models\PelatihanSoalPilihan[] $pelatihanSoalPilihans
 * @property string $aliasModel
 */
abstract class PelatihanSoal extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelatihan_soal';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['unique_id', 'jenis_id', 'kategori_soal_id', 'soal'], 'required'],
            [['jenis_id', 'kategori_soal_id', 'nomor', 'order', 'nilai_maksimum'], 'integer'],
            [['soal', 'pilihan', 'jawaban'], 'string'],
            [['unique_id'], 'string', 'max' => 50],
            [['kategori_soal_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\MasterKategoriSoal::className(), 'targetAttribute' => ['kategori_soal_id' => 'id']],
            [['jenis_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PelatihanSoalJenis::className(), 'targetAttribute' => ['jenis_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unique_id' => 'Unique ID',
            'jenis_id' => 'Jenis ID',
            'kategori_soal_id' => 'Kategori Soal ID',
            'nomor' => 'Nomor',
            'soal' => 'Soal',
            'pilihan' => 'Pilihan',
            'jawaban' => 'Jawaban',
            'order' => 'Order',
            'nilai_maksimum' => 'Nilai Maksimum',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'jawaban' => 'jawaban dari sistem',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKategoriSoal()
    {
        return $this->hasOne(\app\models\MasterKategoriSoal::className(), ['id' => 'kategori_soal_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getJenis()
    {
        return $this->hasOne(\app\models\PelatihanSoalJenis::className(), ['id' => 'jenis_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSoalPesertaJawabans()
    {
        return $this->hasMany(\app\models\PelatihanSoalPesertaJawaban::className(), ['soal_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSoalPilihans()
    {
        return $this->hasMany(\app\models\PelatihanSoalPilihan::className(), ['pelatihan_soal_id' => 'id']);
    }




}
