<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pelatihan_soal_pilihan_ganda".
 *
 * @property integer $id
 * @property integer $pelatihan_soal_id
 * @property integer $jawaban
 *
 * @property \app\models\Pelatihan $pelatihanSoal
 * @property string $aliasModel
 */
abstract class PelatihanSoalPilihanGanda extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelatihan_soal_pilihan_ganda';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pelatihan_soal_id', 'jawaban'], 'required'],
            [['pelatihan_soal_id', 'jawaban'], 'integer'],
            [['pelatihan_soal_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pelatihan::className(), 'targetAttribute' => ['pelatihan_soal_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'pelatihan_soal_id' => 'Pelatihan Soal ID',
            'jawaban' => 'Jawaban',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSoal()
    {
        return $this->hasOne(\app\models\Pelatihan::className(), ['id' => 'pelatihan_soal_id']);
    }




}
