<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pelatihan".
 *
 * @property integer $id
 * @property string $unique_id
 * @property string $nama
 * @property string $latar_belakang
 * @property string $tujuan
 * @property string $kota
 * @property string $nip_penandatangan
 * @property string $nama_penandatangan
 * @property string $tanggal_mulai
 * @property string $tanggal_selesai
 * @property integer $tingkat_id
 * @property integer $status_id
 * @property string $forum_diskusi
 * @property string $lokasi
 * @property string $kriteria
 * @property string $jenis
 * @property integer $jumlah_target
 * @property integer $sasaran
 * @property string $sasaran_wilayah
 * @property string $sumber_dana
 * @property string $hasil_pelaksanaan_pelatihan
 * @property string $dasar_pelaksanaan
 * @property string $absensi_kehadiran
 * @property string $rekapitulasi_nilai
 * @property string $sertifikat
 * @property string $materi_pelatihan
 * @property integer $pelaksana_id
 * @property integer $pelatihan_sebelumnya
 * @property string $proposal
 * @property string $created_at
 * @property integer $created_by
 * @property string $modified_at
 * @property integer $modified_by
 * @property integer $flag
 *
 * @property \app\models\PelatihanTingkat $tingkat
 * @property \app\models\User $pelaksana
 * @property \app\models\PelatihanStatus $status
 * @property \app\models\Pelatihan $pelatihanSebelumnya
 * @property \app\models\Pelatihan[] $pelatihans
 * @property \app\models\PelatihanLampiran[] $pelatihanLampirans
 * @property \app\models\PelatihanPeserta[] $pelatihanPesertas
 * @property \app\models\PelatihanSoalJenis[] $pelatihanSoalJenis
 * @property string $aliasModel
 */
abstract class Pelatihan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pelatihan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nama', 'latar_belakang', 'tujuan', 'kota', 'nip_penandatangan', 'nama_penandatangan', 'tanggal_mulai', 'tingkat_id', 'lokasi', 'kriteria', 'jenis', 'jumlah_target', 'sasaran', 'sasaran_wilayah', 'sumber_dana', 'pelaksana_id', 'created_by', 'modified_by'], 'required'],
            [['latar_belakang', 'tujuan', 'kota', 'nama_penandatangan', 'lokasi', 'hasil_pelaksanaan_pelatihan', 'dasar_pelaksanaan'], 'string'],
            [['tanggal_mulai', 'tanggal_selesai', 'created_at', 'modified_at'], 'safe'],
            [['tingkat_id', 'status_id', 'jumlah_target', 'sasaran', 'pelaksana_id', 'pelatihan_sebelumnya', 'created_by', 'modified_by', 'flag'], 'integer'],
            [['unique_id'], 'string', 'max' => 32],
            [['nama', 'kriteria', 'jenis', 'proposal'], 'string', 'max' => 200],
            [['nip_penandatangan', 'forum_diskusi', 'sasaran_wilayah', 'sumber_dana', 'absensi_kehadiran', 'rekapitulasi_nilai', 'sertifikat', 'materi_pelatihan'], 'string', 'max' => 100],
            [['tingkat_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PelatihanTingkat::className(), 'targetAttribute' => ['tingkat_id' => 'id']],
            [['pelaksana_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['pelaksana_id' => 'id']],
            [['status_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\PelatihanStatus::className(), 'targetAttribute' => ['status_id' => 'id']],
            [['pelatihan_sebelumnya'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Pelatihan::className(), 'targetAttribute' => ['pelatihan_sebelumnya' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'unique_id' => 'Unique ID',
            'nama' => 'Nama',
            'latar_belakang' => 'Latar Belakang',
            'tujuan' => 'Tujuan',
            'kota' => 'Kota',
            'nip_penandatangan' => 'Nip Penandatangan',
            'nama_penandatangan' => 'Nama Penandatangan',
            'tanggal_mulai' => 'Tanggal Mulai',
            'tanggal_selesai' => 'Tanggal Selesai',
            'tingkat_id' => 'Tingkat ID',
            'status_id' => 'Status ID',
            'forum_diskusi' => 'Forum Diskusi',
            'lokasi' => 'Lokasi',
            'kriteria' => 'Kriteria',
            'jenis' => 'Jenis',
            'jumlah_target' => 'Jumlah Target',
            'sasaran' => 'Sasaran',
            'sasaran_wilayah' => 'Sasaran Wilayah',
            'sumber_dana' => 'Sumber Dana',
            'hasil_pelaksanaan_pelatihan' => 'Hasil Pelaksanaan Pelatihan',
            'dasar_pelaksanaan' => 'Dasar Pelaksanaan',
            'absensi_kehadiran' => 'Absensi Kehadiran',
            'rekapitulasi_nilai' => 'Rekapitulasi Nilai',
            'sertifikat' => 'Sertifikat',
            'materi_pelatihan' => 'Materi Pelatihan',
            'pelaksana_id' => 'Pelaksana ID',
            'pelatihan_sebelumnya' => 'Pelatihan Sebelumnya',
            'proposal' => 'Proposal',
            'created_at' => 'Created At',
            'created_by' => 'Created By',
            'modified_at' => 'Modified At',
            'modified_by' => 'Modified By',
            'flag' => 'Flag',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nama' => 'nama pelatihan',
            'tingkat_id' => 'tingkat pelatihan',
            'forum_diskusi' => 'link forum diskusi , ex : link grup whatsapp, telegram, discord',
            'flag' => '0 = deleted , 1 = active',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTingkat()
    {
        return $this->hasOne(\app\models\PelatihanTingkat::className(), ['id' => 'tingkat_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelaksana()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'pelaksana_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(\app\models\PelatihanStatus::className(), ['id' => 'status_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSebelumnya()
    {
        return $this->hasOne(\app\models\Pelatihan::className(), ['id' => 'pelatihan_sebelumnya']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihans()
    {
        return $this->hasMany(\app\models\Pelatihan::className(), ['pelatihan_sebelumnya' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanLampirans()
    {
        return $this->hasMany(\app\models\PelatihanLampiran::className(), ['pelatihan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanPesertas()
    {
        return $this->hasMany(\app\models\PelatihanPeserta::className(), ['pelatihan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanSoalJenis()
    {
        return $this->hasMany(\app\models\PelatihanSoalJenis::className(), ['pelatihan_id' => 'id']);
    }




}
