<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_desa".
 *
 * @property integer $id
 * @property integer $kecamatan_id
 * @property string $nama
 *
 * @property \app\models\PelatihanPeserta[] $pelatihanPesertas
 * @property \app\models\WilayahKecamatan $kecamatan
 * @property string $aliasModel
 */
abstract class WilayahDesa extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_desa';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kecamatan_id', 'nama'], 'required'],
            [['kecamatan_id'], 'integer'],
            [['nama'], 'string', 'max' => 100],
            [['kecamatan_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahKecamatan::className(), 'targetAttribute' => ['kecamatan_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kecamatan_id' => 'Kecamatan ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nama' => 'Nama Desa',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPelatihanPesertas()
    {
        return $this->hasMany(\app\models\PelatihanPeserta::className(), ['desa_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKecamatan()
    {
        return $this->hasOne(\app\models\WilayahKecamatan::className(), ['id' => 'kecamatan_id']);
    }




}
