<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "wilayah_kecamatan".
 *
 * @property integer $id
 * @property integer $kabupaten_id
 * @property string $nama
 *
 * @property \app\models\WilayahDesa[] $wilayahDesas
 * @property \app\models\WilayahKabupaten $kabupaten
 * @property string $aliasModel
 */
abstract class WilayahKecamatan extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'wilayah_kecamatan';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['kabupaten_id', 'nama'], 'required'],
            [['kabupaten_id'], 'integer'],
            [['nama'], 'string', 'max' => 100],
            [['kabupaten_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\WilayahKabupaten::className(), 'targetAttribute' => ['kabupaten_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'kabupaten_id' => 'Kabupaten ID',
            'nama' => 'Nama',
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeHints()
    {
        return array_merge(parent::attributeHints(), [
            'nama' => 'nama kecamatan',
        ]);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getWilayahDesas()
    {
        return $this->hasMany(\app\models\WilayahDesa::className(), ['kecamatan_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getKabupaten()
    {
        return $this->hasOne(\app\models\WilayahKabupaten::className(), ['id' => 'kabupaten_id']);
    }




}
